In [1]:
import pandas as pd
import os

## Melihat Jenis Data

In [15]:
import glob

xx = glob.glob("/home/buddhi/Downloads/sampel/*.xlsx")
xx

['/home/buddhi/Downloads/sampel/Jumlah Kematian Neonatal.xlsx',
 '/home/buddhi/Downloads/sampel/Jumlah Kematian Bayi.xlsx',
 '/home/buddhi/Downloads/sampel/Jumlah Kematian Anak Balita.xlsx']

## Menggabungkan Data Sekaligus Cleaning (Percobaan)

In [17]:
# Folder tempat file-file Excel disimpan
folder_path = "/home/buddhi/Downloads/sampel"  # ganti sesuai folder Anda

# List untuk menampung dataframe tiap file
all_data = []

for file in os.listdir(folder_path):
    if file.endswith(".xlsx"):
        file_path = os.path.join(folder_path, file)

        # Baca data
        df = pd.read_excel(file_path)

        # Tambahkan kolom 'Jenis' sesuai nama file (tanpa .xlsx)
        jenis_value = os.path.splitext(file)[0]
        df["Jenis"] = jenis_value

        # Mapping nama kolom
        new_columns = {}
        for col in df.columns:
            if col.startswith("jumlah"):
                new_columns[col] = "Jumlah"
            elif col != "Jenis":
                new_columns[col] = col.replace("_", " ").title()

        df = df.rename(columns=new_columns)
        
        # Ubah semua value teks jadi kapital di awal kata
        for col in df.select_dtypes(include=["object"]).columns:
            df[col] = df[col].astype(str).str.title()

        # Masukkan ke list
        all_data.append(df)

# Gabungkan semua dataframe
final_df = pd.concat(all_data, ignore_index=True)

# Simpan ke file Excel gabungan
output_file = os.path.join(folder_path, "Data Kematian Gabungan.xlsx")
final_df.to_excel(output_file, index=False)

print(f"Semua file sudah digabung → {output_file}")

Semua file sudah digabung → /home/buddhi/Downloads/sampel/Data Kematian Gabungan.xlsx

In [18]:
pd.read_excel("/home/buddhi/Downloads/sampel/Data Kematian Gabungan.xlsx")

,Id,Kode Provinsi,Nama Provinsi,Kode Kabupaten Kota,Nama Kabupaten Kota,Jumlah,Satuan,Tahun,Jenis
0,1,32,Jawa Barat,3201,Kabupaten Bogor,91,Orang,2019,Jumlah Kematian Neonatal
1,2,32,Jawa Barat,3202,Kabupaten Sukabumi,157,Orang,2019,Jumlah Kematian Neonatal
2,3,32,Jawa Barat,3203,Kabupaten Cianjur,66,Orang,2019,Jumlah Kematian Neonatal
3,4,32,Jawa Barat,3204,Kabupaten Bandung,190,Orang,2019,Jumlah Kematian Neonatal
4,5,32,Jawa Barat,3205,Kabupaten Garut,236,Orang,2019,Jumlah Kematian Neonatal
...,...,...,...,...,...,...,...,...,...
427,131,32,Jawa Barat,3275,Kota Bekasi,4,Orang,2024,Jumlah Kematian Anak Balita
428,132,32,Jawa Barat,3276,Kota Depok,19,Orang,2024,Jumlah Kematian Anak Balita
429,133,32,Jawa Barat,3277,Kota Cimahi,2,Orang,2024,Jumlah Kematian Anak Balita
430,134,32,Jawa Barat,3278,Kota Tasikmalaya,16,Orang,2024,Jumlah Kematian Anak Balita
431,135,32,Jawa Barat,3279,Kota Banjar,13,Orang,2024,Jumlah Kematian Anak Balita

## Menggabungkan Data Sekaligus Cleaning

In [23]:
# Folder tempat file-file Excel disimpan
folder_path = "/home/buddhi/Downloads/sampel 2"  # ganti sesuai folder Anda

# List untuk menampung dataframe tiap file
all_data = []

for file in os.listdir(folder_path):
    if file.endswith(".xlsx"):
        file_path = os.path.join(folder_path, file)

        # Baca data
        df = pd.read_excel(file_path)

        # Mapping nama kolom
        new_columns = {}
        for col in df.columns:
            if col.startswith("jumlah"):
                new_columns[col] = "Jumlah"
            elif col != "Jenis":
                new_columns[col] = col.replace("_", " ").title()

        df = df.rename(columns=new_columns)
        
        # Ubah semua value teks jadi kapital di awal kata
        for col in df.select_dtypes(include=["object"]).columns:
            df[col] = df[col].astype(str).str.title()

        # Tambahkan kolom 'Jenis' sesuai nama file (tanpa .xlsx)
        jenis_value = os.path.splitext(file)[0]
        df["Jenis"] = jenis_value

        # Masukkan ke list
        all_data.append(df)

# Gabungkan semua dataframe
final_df = pd.concat(all_data, ignore_index=True)

# Simpan ke file Excel gabungan
output_file = os.path.join(folder_path, "Data baru.xlsx")
final_df.to_excel(output_file, index=False)

print(f"Semua file sudah digabung → {output_file}")

Semua file sudah digabung → /home/buddhi/Downloads/sampel 2/Data baru.xlsx

In [25]:
zxc = pd.read_excel("/home/buddhi/Downloads/sampel 2/Data baru.xlsx")

In [27]:
zxc.columns

Index(['Id', 'Kode Provinsi', 'Nama Provinsi', 'Kode Kabupaten Kota',
       'Nama Kabupaten Kota', 'Jenis Kelamin', 'Jumlah', 'Satuan', 'Tahun',
       'Jenis'],
      dtype='object')

## Memindahkan Salah Satu Kolom Ke Paling Kanan

In [31]:
# Pastikan df sudah terbentuk
cols = list(zxc.columns)

# Pindahkan 'Jenis Kelamin' ke paling kanan
if "Jenis Kelamin" in cols:
    cols.append(cols.pop(cols.index("Jenis Kelamin")))
    zxc = zxc[cols]

print(zxc.columns)

Index(['Id', 'Kode Provinsi', 'Nama Provinsi', 'Kode Kabupaten Kota',
       'Nama Kabupaten Kota', 'Jumlah', 'Satuan', 'Tahun', 'Jenis',
       'Jenis Kelamin'],
      dtype='object')

In [32]:
zxc

,Id,Kode Provinsi,Nama Provinsi,Kode Kabupaten Kota,Nama Kabupaten Kota,Jumlah,Satuan,Tahun,Jenis,Jenis Kelamin
0,1,32,Jawa Barat,3201,Kabupaten Bogor,1807,Orang,2019,Jumlah Kesembuhan Tuberkulosis Paru Terkonfirm...,Laki-Laki
1,2,32,Jawa Barat,3201,Kabupaten Bogor,1325,Orang,2019,Jumlah Kesembuhan Tuberkulosis Paru Terkonfirm...,Perempuan
2,3,32,Jawa Barat,3202,Kabupaten Sukabumi,1018,Orang,2019,Jumlah Kesembuhan Tuberkulosis Paru Terkonfirm...,Laki-Laki
3,4,32,Jawa Barat,3202,Kabupaten Sukabumi,820,Orang,2019,Jumlah Kesembuhan Tuberkulosis Paru Terkonfirm...,Perempuan
4,5,32,Jawa Barat,3203,Kabupaten Cianjur,492,Orang,2019,Jumlah Kesembuhan Tuberkulosis Paru Terkonfirm...,Laki-Laki
...,...,...,...,...,...,...,...,...,...,...
643,320,32,Jawa Barat,3277,Kota Cimahi,2038,Orang,2024,Jumlah Semua Kasus Tuberkulosis Terdaftar dan ...,Perempuan
644,321,32,Jawa Barat,3278,Kota Tasikmalaya,2180,Orang,2024,Jumlah Semua Kasus Tuberkulosis Terdaftar dan ...,Laki-Laki
645,322,32,Jawa Barat,3278,Kota Tasikmalaya,1838,Orang,2024,Jumlah Semua Kasus Tuberkulosis Terdaftar dan ...,Perempuan
646,323,32,Jawa Barat,3279,Kota Banjar,660,Orang,2024,Jumlah Semua Kasus Tuberkulosis Terdaftar dan ...,Laki-Laki
647,324,32,Jawa Barat,3279,Kota Banjar,420,Orang,2024,Jumlah Semua Kasus Tuberkulosis Terdaftar dan ...,Perempuan

In [35]:
zxc.to_excel("/home/buddhi/Downloads/sampel 2/Data baru 2.xlsx", index=False)